//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZerowasteRecipe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Servings { get; set; }
        public string TotalTime { get; set; }
        public string Ingredient { get; set; }
        public string Carbohydrate { get; set; }
        public string Protien { get; set; }
        public string Fat { get; set; }
        public string Calories { get; set; }
        public string Steps { get; set; }
    }
}
